// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using primeira_api_aspnet.Models;

namespace primeira_api_aspnet.Migrations
{
    [DbContext(typeof(AppDbContext))]
    partial class AppDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .UseIdentityByDefaultColumns()
                .HasAnnotation("Relational:MaxIdentifierLength", 63)
                .HasAnnotation("ProductVersion", "5.0.1");

            modelBuilder.Entity("primeira_api_aspnet.Models.Pessoa", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .UseIdentityByDefaultColumn();

                    b.Property<string>("cpf")
                        .HasColumnType("text");

                    b.Property<int>("endereco")
                        .HasColumnType("integer");

                    b.Property<string>("nome")
                        .HasColumnType("text");

                    b.HasKey("id");

                    b.ToTable("Pessoas");

                    b.HasData(
                        new
                        {
                            id = 1,
                            cpf = "366.325.325-65",
                            endereco = 1,
                            nome = "Maicon"
                        },
                        new
                        {
                            id = 2,
                            cpf = "355.265.888-15",
                            endereco = 2,
                            nome = "Micon"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
